core/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
  path('admin/', admin.site.urls),
  path('newsletter/', include('newsletters.urls', namespace="newsletter")),
  path('dashboard/', include('dashboard.urls', namespace="dashboard")),
]

dashboard/urls.py
from django.urls import path
from .views import DashboardHomeView, NewsLetterDashboardHomeView, NewsLetterCreateView, NewsLetterDetailView, NewsLetterUpdateView, NewsLetterDeleteView


app_name="dashboard"

urlpatterns = [
  path('', DashboardHomeView.as_view(), name="home"),
  path('list/', NewsLetterDashboardHomeView.as_view(), name="list"),
  path('create/', NewsLetterCreateView.as_view(), name="create"),
  path('detail/<int:pk>', NewsLetterDetailView.as_view(), name="detail"),
  path('update/<int:pk>', NewsLetterUpdateView.as_view(), name="update"),
  path('delete/<int:pk>', NewsLetterDeleteView.as_view(), name="delete"),
]

newsletters/urls.py
from django.urls import path
from .views import newsLetterSigNup, newsLetterUnSuscribe

app_name = "news"

urlpatterns = [
  path('signup/', newsLetterSigNup, name="optin"),
  path('unsuscribe/', newsLetterUnSuscribe, name="unsuscribe"),
]

dashboard/models.py
from django.db import models

# Create your models here.

newsletters/models.py
from django.db import models

# Create your models here.
class NewsLetterUser( models.Model ):
  email = models.EmailField( null=False, unique=True )
  date_added = models.DateTimeField( auto_now_add=True )

  def __str__(self):
    return self.email

class NewsLetter( models.Model ):

  EMAILS_STATUS_CHOICES = (
    ('Draft','Draft'),
    ('Published','Published')
  )

  name    = models.CharField( max_length=250 )
  subject = models.CharField( max_length=250 )
  body    = models.TextField( blank=True, null=True )
  email   = models.ManyToManyField( NewsLetterUser )
  created = models.DateTimeField( auto_now_add=True )
  status  = models.CharField( max_length= 10 , choices= EMAILS_STATUS_CHOICES )

  def __str__(self):
    return self.name
  
  class Meta:
    ordering = ('-created',)

newsletters/forms.py
from django import forms
from .models import NewsLetterUser, NewsLetter

class NewsLetterUserSignUpForm( forms.ModelForm ):
  class Meta:
    model  = NewsLetterUser
    fields = ['email']

class NewsLetterCreationForm( forms.ModelForm ):
  class Meta:
    model = NewsLetter
    fields = ['name','subject','body','email','status']

dashboard/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.views.generic import TemplateView, View, UpdateView, DeleteView
from newsletters.models import NewsLetter
from newsletters.forms import NewsLetterCreationForm
from django.conf import settings
from django.core.mail import send_mail, EmailMessage


# Create your views here.
class DashboardHomeView(TemplateView):
  template_name = "dashboard/index.html"


class NewsLetterDashboardHomeView( View ):
  def get(self, request, *args, **kwargs):
    newsletters = NewsLetter.objects.all()

    context = {
      'newsletters': newsletters 
    }

    return render(request, 'dashboard/list.html', context) 

class NewsLetterCreateView( View ):
  def get( self, request, *args, **kwargs):
    form = NewsLetterCreationForm()
    context= {
      'form': form
    }
    return render(request, 'dashboard/create.html', context)

  def post( self, request, *args, **kwargs):

    if request.method=="POST":
      form = NewsLetterCreationForm(request.POST or None)
      if form.is_valid():
        instance = form.save()
        newsletter = NewsLetter.objects.get( id = instance.id )

        if newsletter.status == "Published":
          subject = newsletter.subject
          body = newsletter.body
          from_email = settings.EMAIL_HOST_USER
          for email in newsletter.email.all():
            send_mail( subject = subject, from_email = from_email, recipient_list = [email], message = body, fail_silently = True )
        return redirect('dashboard:list') 
      
    context= {

    }
    return render(request, 'dashboard/create.html', context)
    

class NewsLetterDetailView( View ):
  def get(self, request, *args, pk, **kwargs):
    newsletter = get_object_or_404( NewsLetter, pk = pk)
    context = {
      'newsletter':newsletter
    }
    return render( request, 'dashboard/detail.html', context )
  
class NewsLetterUpdateView(UpdateView):
  model = NewsLetter
  form_class = NewsLetterCreationForm
  template_name = 'dashboard/update.html'
  success_url = '/dashboard/detail/3/'
  
  def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      context.update({
        'view_type': 'update'
      })  
      return context
  
  

  def post( self, request, pk, *args, **kwargs):
    newsletter = get_object_or_404( NewsLetter, pk = pk)

    if request.method=="POST":
      form = NewsLetterCreationForm(request.POST or None)
      if form.is_valid():
        instance = form.save()
        newsletter = NewsLetter.objects.get( id = instance.id )

        if newsletter.status == "Published":
          subject = newsletter.subject
          body = newsletter.body
          from_email = settings.EMAIL_HOST_USER
          for email in newsletter.email.all():
            send_mail( subject = subject, from_email = from_email, recipient_list = [email], message = body, fail_silently = True )
        return redirect('dashboard:detail', pk = newsletter.id) 
    else:
      form = NewsLetterCreationForm( instance= newsletter )
    context= {

    }
    return render(request, 'dashboard/update.html', context)
  
class NewsLetterDeleteView( DeleteView ):
  model = NewsLetter
  template_name = 'dashboard/remove.html' 
  success_url = '/dashboard/list/'

newsletters/views.py
from django.contrib import messages
from django.core.mail import send_mail, EmailMessage

from django.conf import settings 
from django.shortcuts import render

from .models import NewsLetterUser
from .forms import NewsLetterUserSignUpForm
from django.template.loader import render_to_string


# Create your views here.

def newsLetterSigNup( request ):
  form = NewsLetterUserSignUpForm( request.POST or None )
  if form.is_valid():
    instance = form.save( commit= False )
    if NewsLetterUser.objects.filter( email = instance.email ).exists():
      messages.warning( request, 'Email already exist ')
    
    else:
      instance.save()
      messages.success( request, 'We sent an email to your email addrees, open to continued...')
      subject = 'Computer Books'
      fromEmail = settings.EMAIL_HOST_USER
      toEmail=[ instance.email ]
      
      htmlTemplate = 'newsletter/email_templates/welcome.html'
      htmlMessage = render_to_string(htmlTemplate)
      message = EmailMessage( subject, htmlMessage, fromEmail, toEmail )
      message.content_subtype = 'html'
      message.send()
  
  context = { 'form':form }
  return render( request, 'start-here.html', context )


def newsLetterUnSuscribe( request ):
  form = NewsLetterUserSignUpForm( request.POST or None )
  if form.is_valid():
    instance = form.save( commit= False )
    if NewsLetterUser.objects.filter( email = instance.email ).exists():
      NewsLetterUser.objects.filter( email = instance.email ).delete()
      messages.success( request, 'Email removed')
    else:
      print('Email not found')
      messages.warning( request, 'Email not found')

  context = {
    "form": form
  }
  return render( request, 'un_suscribe.html', context )

templates/base.html
{% load tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>NewsLetter</title>
  {% tailwind_css %}
</head>
<body>  
  {% block messages %}{% include 'messages.html' %}{% endblock messages %}

  {% block content %}
    
  {% endblock content %}
    
</body>
</html>

templates/dashboard/create.html
{% extends 'base.html' %}


{% block content %}
  
<!-- This example requires Tailwind CSS v3.0+ -->
<div class="isolate bg-white">
  <div class="absolute inset-x-0 top-[-10rem] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[-20rem]">
    <svg class="relative left-[calc(50%-11rem)] -z-10 h-[21.1875rem] max-w-none -translate-x-1/2 rotate-[30deg] sm:left-[calc(50%-30rem)] sm:h-[42.375rem]" viewBox="0 0 1155 678" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path fill="url(#45de2b6b-92d5-4d68-a6a0-9b9b2abad533)" fill-opacity=".3" d="M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z" />
      <defs>
        <linearGradient id="45de2b6b-92d5-4d68-a6a0-9b9b2abad533" x1="1155.49" x2="-78.208" y1=".177" y2="474.645" gradientUnits="userSpaceOnUse">
          <stop stop-color="#9089FC"></stop>
          <stop offset="1" stop-color="#FF80B5"></stop>
        </linearGradient>
      </defs>
    </svg>
  </div>
  <div class="px-6 pt-6 lg:px-8">
    <div>
      <nav class="flex h-9 items-center justify-between" aria-label="Global">
        <div class="flex lg:min-w-0 lg:flex-1" aria-label="Global">
          <a href="#" class="-m-1.5 p-1.5">
            <span class="sr-only">Your Company</span>
            <img class="h-8" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="">
          </a>
        </div>
        <div class="flex lg:hidden">
          <button type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
            <span class="sr-only">Open main menu</span>
            <!-- Heroicon name: outline/bars-3 -->
            <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
            </svg>
          </button>
        </div>
        <div class="hidden lg:flex lg:min-w-0 lg:flex-1 lg:justify-center lg:gap-x-12">
          <a href="{% url 'dashboard:home' %}" class="font-semibold text-gray-900 hover:text-gray-900">Product</a>

          <a href="{% url 'dashboard:list' %}" class="font-semibold text-gray-900 hover:text-gray-900">BroadCast List</a>

        </div>
        <div class="hidden lg:flex lg:min-w-0 lg:flex-1 lg:justify-end">
          <a href="#" class="inline-block rounded-lg px-3 py-1.5 text-sm font-semibold leading-6 text-gray-900 shadow-sm ring-1 ring-gray-900/10 hover:ring-gray-900/20">Log in</a>
        </div>
      </nav>
      <!-- Mobile menu, show/hide based on menu open state. -->
      <div role="dialog" aria-modal="true" >
        <div focus="true" class="fixed inset-0 z-10 overflow-y-auto bg-white px-6 py-6 lg:hidden">
          <div class="flex h-9 items-center justify-between">
            <div class="flex">
              <a href="#" class="-m-1.5 p-1.5">
                <span class="sr-only">Your Company</span>
                <img class="h-8" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="">
              </a>
            </div>
            <div class="flex">
              <button type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
                <span class="sr-only">Close menu</span>
                <!-- Heroicon name: outline/x-mark -->
                <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
          </div>
          <div class="mt-6 flow-root">
            <div class="-my-6 divide-y divide-gray-500/10">
              <div class="space-y-2 py-6">
                <a href="#" class="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-400/10">Product</a>

                <a href="#" class="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-400/10">Features</a>

                <a href="#" class="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-400/10">Marketplace</a>

                <a href="#" class="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-400/10">Company</a>
              </div>
              <div class="py-6">
                <a href="#" class="-mx-3 block rounded-lg py-2.5 px-3 text-base font-semibold leading-6 text-gray-900 hover:bg-gray-400/10">Log in</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <main>
    <div class="relative px-6 lg:px-8">
      <div class="mx-auto max-w-3xl pt-10 pb-32 sm:pt-28 sm:pb-40">
        <div>
          <div>
            <h1 class="text-4xl font-bold tracking-tight sm:text-center sm:text-6xl">Data to enrich your online business</h1>
            <p class="mt-6 text-lg leading-8 text-gray-600 sm:text-center">Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat fugiat aliqua.</p>

          <div>
            <div class="mt-8 flex gap-x-4 sm:justify-center">
              <form action="" method="POST">
                {% csrf_token %}
                <label class="block text-sm font-medium dark:text-dark-txt text-gray-700">
                  Name
                </label>
                {{ form.name }}

                <label class="block text-sm font-medium dark:text-dark-txt text-gray-700">
                  Subject
                </label>
                {{ form.subject }}
                
                <label class="block text-sm font-medium dark:text-dark-txt text-gray-700">
                  Email
                </label>
                {{ form.email }}
                
                <label class="block text-sm font-medium dark:text-dark-txt text-gray-700">
                  Body
                </label>
                {{ form.body }}
                
                <label class="block text-sm font-medium dark:text-dark-txt text-gray-700">
                  Status
                </label>
                {{ form.status }}
                
                <button type="submit" class="px-3 py-2 bg-blue-500 rounded-lg text-white">Submit</button>
              </form>
            </div>
          </div>
          <div class="absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-30rem)]">
            <svg class="relative left-[calc(50%+3rem)] h-[21.1875rem] max-w-none -translate-x-1/2 sm:left-[calc(50%+36rem)] sm:h-[42.375rem]" viewBox="0 0 1155 678" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path fill="url(#ecb5b0c9-546c-4772-8c71-4d3f06d544bc)" fill-opacity=".3" d="M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z" />
              <defs>
                <linearGradient id="ecb5b0c9-546c-4772-8c71-4d3f06d544bc" x1="1155.49" x2="-78.208" y1=".177" y2="474.645" gradientUnits="userSpaceOnUse">
                  <stop stop-color="#9089FC"></stop>
                  <stop offset="1" stop-color="#FF80B5"></stop>
                </linearGradient>
              </defs>
            </svg>
          </div>
        </div>
      </div>
    </div>
  </main>
</div>



{% endblock content %}
  

templates/dashboard/detail.html
{% extends 'base.html' %}


{% block content %}
  
<!-- This example requires Tailwind CSS v3.0+ -->
<div class="isolate bg-white">
  <div class="absolute inset-x-0 top-[-10rem] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[-20rem]">
    <svg class="relative left-[calc(50%-11rem)] -z-10 h-[21.1875rem] max-w-none -translate-x-1/2 rotate-[30deg] sm:left-[calc(50%-30rem)] sm:h-[42.375rem]" viewBox="0 0 1155 678" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path fill="url(#45de2b6b-92d5-4d68-a6a0-9b9b2abad533)" fill-opacity=".3" d="M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z" />
      <defs>
        <linearGradient id="45de2b6b-92d5-4d68-a6a0-9b9b2abad533" x1="1155.49" x2="-78.208" y1=".177" y2="474.645" gradientUnits="userSpaceOnUse">
          <stop stop-color="#9089FC"></stop>
          <stop offset="1" stop-color="#FF80B5"></stop>
        </linearGradient>
      </defs>
    </svg>
  </div>
  <div class="px-6 pt-6 lg:px-8">
    <div>
      <nav class="flex h-9 items-center justify-between" aria-label="Global">
        <div class="flex lg:min-w-0 lg:flex-1" aria-label="Global">
          <a href="#" class="-m-1.5 p-1.5">
            <span class="sr-only">Your Company</span>
            <img class="h-8" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="">
          </a>
        </div>
        <div class="flex lg:hidden">
          <button type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
            <span class="sr-only">Open main menu</span>
            <!-- Heroicon name: outline/bars-3 -->
            <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
            </svg>
          </button>
        </div>
        <div class="hidden lg:flex lg:min-w-0 lg:flex-1 lg:justify-center lg:gap-x-12">
          <a href="{% url 'dashboard:home' %}" class="font-semibold text-gray-900 hover:text-gray-900">Product</a>

          <a href="{% url 'dashboard:list' %}" class="font-semibold text-gray-900 hover:text-gray-900">BroadCast List</a>

        </div>
        <div class="hidden lg:flex lg:min-w-0 lg:flex-1 lg:justify-end">
          <a href="#" class="inline-block rounded-lg px-3 py-1.5 text-sm font-semibold leading-6 text-gray-900 shadow-sm ring-1 ring-gray-900/10 hover:ring-gray-900/20">Log in</a>
        </div>
      </nav>
      <!-- Mobile menu, show/hide based on menu open state. -->
      <div role="dialog" aria-modal="true" >
        <div focus="true" class="fixed inset-0 z-10 overflow-y-auto bg-white px-6 py-6 lg:hidden">
          <div class="flex h-9 items-center justify-between">
            <div class="flex">
              <a href="#" class="-m-1.5 p-1.5">
                <span class="sr-only">Your Company</span>
                <img class="h-8" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="">
              </a>
            </div>
            <div class="flex">
              <button type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
                <span class="sr-only">Close menu</span>
                <!-- Heroicon name: outline/x-mark -->
                <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
          </div>
          <div class="mt-6 flow-root">
            <div class="-my-6 divide-y divide-gray-500/10">
              <div class="space-y-2 py-6">
                <a href="#" class="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-400/10">Product</a>

                <a href="#" class="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-400/10">Features</a>

                <a href="#" class="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-400/10">Marketplace</a>

                <a href="#" class="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-400/10">Company</a>
              </div>
              <div class="py-6">
                <a href="#" class="-mx-3 block rounded-lg py-2.5 px-3 text-base font-semibold leading-6 text-gray-900 hover:bg-gray-400/10">Log in</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <main>
    <div class="relative px-6 lg:px-8">
      <div class="mx-auto max-w-3xl pt-10 pb-32 sm:pt-28 sm:pb-40">
        <div>
          <div class="justify-start">
            <h1 class="text-4xl font-bold tracking-tight sm:text-center sm:text-6xl">Data to enrich your online business</h1>
            <p class="mt-6 text-lg leading-8 text-gray-600 sm:text-center"> Newsletter Detail: {{ newsletter.name }}  
              <a href="{% url 'dashboard:create' %}" class="inline-block px-6 py-2.5 bg-green-200 text-black font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-green-300 hover:shadow-lg focus:bg-green-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out">Update </a>   
            
              <a href="{% url 'dashboard:create' %}" class="inline-block px-6 py-2.5 bg-red-200 text-black font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-red-300 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out">Remove</a> 
            </p>
           
          <div>
            <div class="mt-8 gap-x-4 justify-center">
              <h1>
                <span class="block text-base text-center text-indigo-600 font-semibold tracking-wide uppercase">
                Subject:</span>
                <span class="mt-2 block text-3xl text-center leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">
                {{newsletter.subject}}</span>
              </h1>
              <br>
              <div class="mt-6 prose prose-indigo prose-lg text-gray-500 mx-auto">
                <p class="text-center">{{newsletter.body}}</p>
              </div>
            </div>
          </div>
          <div class="absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-30rem)]">
            <svg class="relative left-[calc(50%+3rem)] h-[21.1875rem] max-w-none -translate-x-1/2 sm:left-[calc(50%+36rem)] sm:h-[42.375rem]" viewBox="0 0 1155 678" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path fill="url(#ecb5b0c9-546c-4772-8c71-4d3f06d544bc)" fill-opacity=".3" d="M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z" />
              <defs>
                <linearGradient id="ecb5b0c9-546c-4772-8c71-4d3f06d544bc" x1="1155.49" x2="-78.208" y1=".177" y2="474.645" gradientUnits="userSpaceOnUse">
                  <stop stop-color="#9089FC"></stop>
                  <stop offset="1" stop-color="#FF80B5"></stop>
                </linearGradient>
              </defs>
            </svg>
          </div>
        </div>
      </div>
    </div>
  </main>
</div>



{% endblock content %}
  

templates/newsletter/email_templates/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Welcome</title>
</head>
<body>
  <h2>Welcome to Mailtrap</h2>
  <p>Here we'll send you important information</p>
</body>
</html>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>